improve zimuku tv show search ability
gyh1621/GetSubtitles pull request #66
Opened 2020-04-03 02:37 UTC by megaslx

改善zimuku对pt、bt站下载的剧集的搜索能力
1、搜索关键字使用全中文的第X季来搜索，否则经常搜不出东西
2、针对字幕库很多只有一季的剧集，搜索结果页面标题不包含季的问题，抽样其中的第一个字幕连接的文本来补充判断
3、对compute_subtitle_score增加判断发布组是否匹配，避免下载时间轴错误的字幕

2020-04-04 06:48 UTC, gyh1621 requested changes

2020-04-04 06:48 UTC, gyh1621 commented on getsub/downloader/zimuku.py
> +                            season_cn1 = re.search("第(.*)季", title).group(1).strip()
```python3
try:
    title = title_a.text
    season_cn1 = re.search("第(.*)季", title).group(1).strip()
except AttributeError:
    sample_title = .....
    ....
    season_cn1 = num_to_cn(str(sample_dict['season']))

2020-04-04 06:48 UTC, gyh1621 commented on getsub/util.py
> +    video_group = video_detail["release_group"].lower()
`video_group = video_detail.get("release_group", "").lower()`

2020-04-04 06:48 UTC, gyh1621 commented on getsub/util.py
> +    sub_group = sub_name_info["release_group"].lower()
`sub_group = sub_name_info.get("release_group", "").lower()`

2020-04-04 06:48 UTC, gyh1621 commented on getsub/util.py
> +        if video_name in sub_title:
改回 ==。
比如剧 “Broke” 和剧 “Two broke girls”，后者包含了前者的全称。

2020-04-04 06:48 UTC, gyh1621 commented on getsub/util.py
> +            elif video_group not in sub_group:
强制的条件移到最前面吧（判断 video_name 之前）
```python3
if video_group and sub_group:
    if video_group != sub_group:
        return -1  # release group not match
elif video_group or sub_group:
    return -1  # release group not match
if video_name == sub_title:
    ....

2020-04-04 06:51 UTC, gyh1621 commented
提交前麻烦先检查下代码风格：
```shell
flake8 --max-line-length=120 ./
black ./
```
跑一遍测试：
```shell
python -m unittest discover -b
```

2020-04-04 14:58 UTC, megaslx commented on getsub/util.py
> +        if video_name in sub_title:
这个的确可能造成错误，不过更大的问题是目前字幕库在链接文本里不仅仅包含了视频文件的全名，还在前面增加了中英文、字幕组之类的额外信息，如果只是用目前的extract_name，去掉中文，都会导致title多很多东西，用==的话基本配不到了

2020-04-04 21:34 UTC, gyh1621 commented on getsub/util.py
> +        if video_name in sub_title:
`extract_name` 我在 bazarr 的 zimuku 里改成了[匹配名字里的最长英文子串](https://github.com/morpheus65535/bazarr/blob/development/libs/subliminal_patch/providers/zimuku.py#L301-L339)，效果应该比现在的单纯过滤中文好很多。

2020-04-06 13:10 UTC, megaslx commented
问题比较多，还需要再研究一下代码

2020-04-06 13:10 UTC, closed without merging

2020-04-12 20:55 UTC, gyh1621 commented
你好，这两天我要发一个新版，你的第二点我去看了下确实存在（第一点我没找到具体例子）。你还想提PR吗，不然我这次把第二点一起修了。

2020-04-14 02:46 UTC, megaslx commented
> 
> 
> 你好，这两天我要发一个新版，你的第二点我去看了下确实存在（第一点我没找到具体例子）。你还想提PR吗，不然我这次把第二点一起修了。

不提了，我发现为啥我提交的代码测试不通了，我在pypi上下载的发行版上改的代码，和github上目前的版本其实是有点差别的，所以有些地方就不通了。
这两天我发现了另两个问题：
1、有些字幕组发的压缩包里面，他的字幕文件的命名不太规范，或者都是中文之类的，直接用compute方法来计算分数可能找不出可用的字幕文件，这个方法能增加一个新的参数，只进行语言打分，不做别的判断吗？这样可以一定程度解决这个问题。
2、有些字幕组在上传sup格式的字幕，这个好像不在sub_format里面，不知能否增加以下。

2020-04-16 07:19 UTC, gyh1621 commented
> > 你好，这两天我要发一个新版，你的第二点我去看了下确实存在（第一点我没找到具体例子）。你还想提PR吗，不然我这次把第二点一起修了。
> 
> 不提了，我发现为啥我提交的代码测试不通了，我在pypi上下载的发行版上改的代码，和github上目前的版本其实是有点差别的，所以有些地方就不通了。
> 这两天我发现了另两个问题：
> 1、有些字幕组发的压缩包里面，他的字幕文件的命名不太规范，或者都是中文之类的，直接用compute方法来计算分数可能找不出可用的字幕文件，这个方法能增加一个新的参数，只进行语言打分，不做别的判断吗？这样可以一定程度解决这个问题。
> 2、有些字幕组在上传sup格式的字幕，这个好像不在sub_format里面，不知能否增加以下。

第一点给个例子

2020-04-16 08:19 UTC, gyh1621 commented
更新到了 1.7.7:
- [x] 针对字幕库很多只有一季的剧集，搜索结果页面标题不包含季的问题，抽样其中的第一个字幕连接的文本来补充判断
- [x] 有些字幕组在上传sup格式的字幕

字幕包文件命名的问题请带上例子开个新 issue 吧。